# This is the Android NDK make file for openNURBS shared library for Android.
# dan@mcneel.com
# Last Revised: 10/07/13

LOCAL_PATH := $(call my-dir)

include $(call all-subdir-makefiles)
include $(CLEAR_VARS)
LOCAL_MODULE := opennurbs
LOCAL_SRC_FILES := ../on_3dm_attributes.cpp \
		../on_3dm_settings.cpp \
		../on_annotation2.cpp \
		../on_arc.cpp \
		../on_arccurve.cpp \
		../on_archive.cpp \
		../on_array.cpp \
		../on_beam.cpp \
		../on_bezier.cpp \
		../on_brep.cpp \
		../on_circle.cpp \
		../on_curve.cpp \
		../on_defines.cpp \
		../on_detail.cpp \
		../on_dimstyle.cpp \
		../on_geometry.cpp \
		../on_hatch.cpp \
		../on_instance.cpp \
		../on_intersect.cpp \
		../on_layer.cpp \
		../on_light.cpp \
		../on_line.cpp \
		../on_linecurve.cpp \
		../on_linetype.cpp \
		../on_massprop.cpp \
		../on_material.cpp \
		../on_mesh.cpp \
		../on_nurbscurve.cpp \
		../on_nurbssurface.cpp \
		../on_object.cpp \
		../on_plane.cpp \
		../on_planesurface.cpp \
		../on_plus.cpp \
		../on_point.cpp \
		../on_pointcloud.cpp \
		../on_pointgeometry.cpp \
		../on_pointgrid.cpp \
		../on_polycurve.cpp \
		../on_polylinecurve.cpp \
		../on_quaternion.cpp \
		../on_rtree.cpp \
		../on_sphere.cpp \
		../on_surface.cpp \
		../on_textlog.cpp \
		../on_userdata.cpp \
		../on_viewport.cpp \
		../on_xform.cpp \
		../stringholder.cpp \
		../stdafx.cpp \
		../opennurbs/opennurbs_3dm_attributes.cpp \
		../opennurbs/opennurbs_3dm_properties.cpp \
		../opennurbs/opennurbs_3dm_settings.cpp \
		../opennurbs/opennurbs_annotation.cpp \
		../opennurbs/opennurbs_annotation2.cpp \
		../opennurbs/opennurbs_arc.cpp \
		../opennurbs/opennurbs_arccurve.cpp \
		../opennurbs/opennurbs_archive.cpp \
		../opennurbs/opennurbs_array.cpp \
		../opennurbs/opennurbs_base32.cpp \
		../opennurbs/opennurbs_base64.cpp \
		../opennurbs/opennurbs_beam.cpp \
		../opennurbs/opennurbs_bezier.cpp \
		../opennurbs/opennurbs_beziervolume.cpp \
		../opennurbs/opennurbs_bitmap.cpp \
		../opennurbs/opennurbs_bounding_box.cpp \
		../opennurbs/opennurbs_box.cpp \
		../opennurbs/opennurbs_brep.cpp \
		../opennurbs/opennurbs_brep_extrude.cpp \
		../opennurbs/opennurbs_brep_io.cpp \
		../opennurbs/opennurbs_brep_isvalid.cpp \
		../opennurbs/opennurbs_brep_region.cpp \
		../opennurbs/opennurbs_brep_tools.cpp \
		../opennurbs/opennurbs_brep_v2valid.cpp \
		../opennurbs/opennurbs_circle.cpp \
		../opennurbs/opennurbs_color.cpp \
		../opennurbs/opennurbs_compress.cpp \
		../opennurbs/opennurbs_cone.cpp \
		../opennurbs/opennurbs_crc.cpp \
		../opennurbs/opennurbs_curve.cpp \
		../opennurbs/opennurbs_curveonsurface.cpp \
		../opennurbs/opennurbs_curveproxy.cpp \
		../opennurbs/opennurbs_cylinder.cpp \
		../opennurbs/opennurbs_defines.cpp \
		../opennurbs/opennurbs_detail.cpp \
		../opennurbs/opennurbs_dimstyle.cpp \
		../opennurbs/opennurbs_ellipse.cpp \
		../opennurbs/opennurbs_embedded_file.cpp \
		../opennurbs/opennurbs_error.cpp \
		../opennurbs/opennurbs_error_message.cpp \
		../opennurbs/opennurbs_evaluate_nurbs.cpp \
		../opennurbs/opennurbs_extensions.cpp \
		../opennurbs/opennurbs_font.cpp \
		../opennurbs/opennurbs_fsp.cpp \
		../opennurbs/opennurbs_geometry.cpp \
		../opennurbs/opennurbs_group.cpp \
		../opennurbs/opennurbs_hatch.cpp \
		../opennurbs/opennurbs_instance.cpp \
		../opennurbs/opennurbs_intersect.cpp \
		../opennurbs/opennurbs_knot.cpp \
		../opennurbs/opennurbs_layer.cpp \
		../opennurbs/opennurbs_light.cpp \
		../opennurbs/opennurbs_line.cpp \
		../opennurbs/opennurbs_linecurve.cpp \
		../opennurbs/opennurbs_linetype.cpp \
		../opennurbs/opennurbs_lookup.cpp \
		../opennurbs/opennurbs_material.cpp \
		../opennurbs/opennurbs_math.cpp \
		../opennurbs/opennurbs_matrix.cpp \
		../opennurbs/opennurbs_memory.c \
		../opennurbs/opennurbs_memory_util.c \
		../opennurbs/opennurbs_mesh.cpp \
		../opennurbs/opennurbs_mesh_ngon.cpp \
		../opennurbs/opennurbs_mesh_tools.cpp \
		../opennurbs/opennurbs_morph.cpp \
		../opennurbs/opennurbs_nurbscurve.cpp \
		../opennurbs/opennurbs_nurbssurface.cpp \
		../opennurbs/opennurbs_nurbsvolume.cpp \
		../opennurbs/opennurbs_object.cpp \
		../opennurbs/opennurbs_object_history.cpp \
		../opennurbs/opennurbs_objref.cpp \
		../opennurbs/opennurbs_offsetsurface.cpp \
		../opennurbs/opennurbs_optimize.cpp \
		../opennurbs/opennurbs_photogrammetry.cpp \
		../opennurbs/opennurbs_plane.cpp \
		../opennurbs/opennurbs_planesurface.cpp \
		../opennurbs/opennurbs_pluginlist.cpp \
		../opennurbs/opennurbs_point.cpp \
		../opennurbs/opennurbs_pointcloud.cpp \
		../opennurbs/opennurbs_pointgeometry.cpp \
		../opennurbs/opennurbs_pointgrid.cpp \
		../opennurbs/opennurbs_polycurve.cpp \
		../opennurbs/opennurbs_polyedgecurve.cpp \
		../opennurbs/opennurbs_polyline.cpp \
		../opennurbs/opennurbs_polylinecurve.cpp \
		../opennurbs/opennurbs_quaternion.cpp \
		../opennurbs/opennurbs_rand.cpp \
		../opennurbs/opennurbs_revsurface.cpp \
		../opennurbs/opennurbs_rtree.cpp \
		../opennurbs/opennurbs_sort.cpp \
		../opennurbs/opennurbs_sphere.cpp \
		../opennurbs/opennurbs_string.cpp \
		../opennurbs/opennurbs_sum.cpp \
		../opennurbs/opennurbs_sumsurface.cpp \
		../opennurbs/opennurbs_surface.cpp \
		../opennurbs/opennurbs_surfaceproxy.cpp \
		../opennurbs/opennurbs_textlog.cpp \
		../opennurbs/opennurbs_torus.cpp \
		../opennurbs/opennurbs_unicode.cpp \
		../opennurbs/opennurbs_userdata.cpp \
		../opennurbs/opennurbs_uuid.cpp \
		../opennurbs/opennurbs_viewport.cpp \
		../opennurbs/opennurbs_workspace.cpp \
		../opennurbs/opennurbs_wstring.cpp \
		../opennurbs/opennurbs_xform.cpp \
		../opennurbs/opennurbs_zlib.cpp \
		../opennurbs/opennurbs_zlib_memory.cpp \
		../opennurbs/zlib/adler32.c \
		../opennurbs/zlib/compress.c \
		../opennurbs/zlib/crc32.c \
		../opennurbs/zlib/deflate.c \
		../opennurbs/zlib/infback.c \
		../opennurbs/zlib/inffast.c \
		../opennurbs/zlib/inflate.c \
		../opennurbs/zlib/inftrees.c \
		../opennurbs/zlib/trees.c \
		../opennurbs/zlib/uncompr.c \
		../opennurbs/zlib/zutil.c
		
LOCAL_CFLAGS := -DOPENNURBS_SDK -DOPENNURBS_BUILD -DMONO_BUILD -DON_COMPILER_ANDROIDNDK 
LOCAL_CPPFLAGS := -DOPENNURBS_SDK -DOPENNURBS_BUILD -DMONO_BUILD -DON_COMPILER_ANDROIDNDK -D__GXX_EXPERIMENTAL_CXX0X__ -std=c++11
LOCAL_LDLIBS := -llog -lGLESv2 -landroid -lEGL
include $(BUILD_SHARED_LIBRARY)