//public enum GumballMode { }
//public enum GumballPopupMenuItem { }
//public class GumballDrawSettings { }
//public class GumballFrame { }
//public class GumballAppearance { }
//public class GumballPickResult { }
//public class RhinoGumball { }
//public class GumballPopUpMenu { }
//public class GumballDisplayConduit { }
//public class GumballDragger { }
