// !!!DO NOT EDIT THIS FILE BY HAND!!!
// Create this file by running MethodGen.exe in the rhinocommon directory
// MethodGen.exe parses the cpp files in rhcommon_c to create C# callable
// function declarations

using System;
using System.Runtime.InteropServices;
using Rhino;
using Rhino.Geometry;
using Rhino.Geometry.Intersect;
using Rhino.Collections;
using Rhino.Display;

// Atuomatically generated function declarations for calling into
// the support 'C' DLL (rhcommon_c.dll).
internal partial class UnsafeNativeMethods
{
  #region rdk_color.cpp
  //unsigned int Rdk_ColorBlend(float t, unsigned int from_argb, unsigned int to_argb)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern uint Rdk_ColorBlend(float t, uint from_argb, uint to_argb);
  #endregion


  #region rdk_content.cpp
  //void Rdk_SetContentStringCallback(RDK_GETCONTENTSTRINGPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetAddUISectionsCallback(RDK_ADDUISECTIONSPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetRenderContentDeleteThisCallback(RDK_RENDERCONTENTDELETETHISPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetIsContentTypeAcceptableAsChildCallback(RDK_ISCONTENTTYPEACCEPTABLEASCHILDPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetHarvestDataCallback(RDK_HARVESTDATAPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_CallAddUISectionsBase(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_CallAddUISectionsBase(IntPtr pContent);

  //void Rdk_AddUISections(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_AddUISections(IntPtr pContent);

  //int Rdk_RenderContent_CallHarvestDataBase(CRhRdkContent* pContent, const CRhRdkContent* pOldContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_CallHarvestDataBase(IntPtr pContent, IntPtr pOldContent);

  //int Rdk_RenderContent_HarvestData(CRhRdkContent* pContent, const CRhRdkContent* pOldContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_HarvestData(IntPtr pContent, IntPtr pOldContent);

  //int Rdk_RenderContent_CallIsContentTypeAcceptableAsChildBase(const CRhRdkContent* pContent, ON_UUID uuidType, RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_CallIsContentTypeAcceptableAsChildBase(IntPtr pContent, Guid uuidType, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int Rdk_RenderContent_IsContentTypeAcceptableAsChild(const CRhRdkContent* pContent, ON_UUID uuidType, RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_IsContentTypeAcceptableAsChild(IntPtr pContent, Guid uuidType, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int CRhCmnRenderContent_IsRhCmnDefined(const CRhRdkContent* pRenderContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int CRhCmnRenderContent_IsRhCmnDefined(IntPtr pRenderContent);

  //void Rdk_RenderContent_DeleteThis(CRhRdkContent* pRenderContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_DeleteThis(IntPtr pRenderContent);

  //void Rdk_RenderContent_ChildSlotNameFromParamName(CRhRdkContent* pContent, const RHMONO_STRING* _sParamName, CRhCmnStringHolder* pSH)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_ChildSlotNameFromParamName(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _sParamName, IntPtr pSH);

  //void Rdk_RenderContent_ParamNameFromChildSlotName(CRhRdkContent* pContent, const RHMONO_STRING* _sChildSlotName, CRhCmnStringHolder* pSH)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_ParamNameFromChildSlotName(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _sChildSlotName, IntPtr pSH);

  //CRhRdkContent* Rdk_RenderContent_FindChild(CRhRdkContent* pContent, const RHMONO_STRING* _sChildSlotName)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_RenderContent_FindChild(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _sChildSlotName);

  //void Rdk_RenderContent_SetChildSlotName(CRhRdkContent* pContent, const RHMONO_STRING* _sChildSlotName)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_SetChildSlotName(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _sChildSlotName);

  //int Rdk_RenderContent_IsTopLevel(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_IsTopLevel(IntPtr pContent);

  //int Rdk_RenderContent_IsInDocument(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_IsInDocument(IntPtr pContent);

  //int Rdk_RenderContent_IsHidden(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_IsHidden(IntPtr pContent);

  //int Rdk_RenderContent_IsCurrent(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_IsCurrent(IntPtr pContent);

  //void Rdk_RenderContent_SetIsHidden(CRhRdkContent* pContent, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_SetIsHidden(IntPtr pContent, [MarshalAs(UnmanagedType.U1)]bool b);

  //int Rdk_RenderContent_IsKind(CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_IsKind(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //CRhRdkContent* Rdk_RenderContent_TopLevelParent(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_RenderContent_TopLevelParent(IntPtr pContent);

  //CRhRdkTexture* Rdk_RenderContent_DynamicCastToTexture(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_RenderContent_DynamicCastToTexture(IntPtr pContent);

  //CRhRdkEnvironment* Rdk_RenderContent_DynamicCastToEnvironment(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_RenderContent_DynamicCastToEnvironment(IntPtr pContent);

  //CRhRdkMaterial* Rdk_RenderContent_DynamicCastToMaterial(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_RenderContent_DynamicCastToMaterial(IntPtr pContent);

  //void Rdk_RenderContent_GetString(const CRhRdkContent* pConstContent, CRhCmnStringHolder* pSH, int which)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetString(IntPtr pConstContent, IntPtr pSH, int which);

  //void Rdk_RenderContent_SetInstanceName(CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_SetInstanceName(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //void Rdk_RenderContent_SetNotes(CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_SetNotes(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //ON_UUID Rdk_RenderContent_InstanceId(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_RenderContent_InstanceId(IntPtr pContent);

  //void Rdk_RenderContent_SetInstanceId(CRhRdkContent* pContent, ON_UUID uuid)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_SetInstanceId(IntPtr pContent, Guid uuid);

  //CRhRdkContent* Rdk_FindContentInstance(ON_UUID instanceId)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_FindContentInstance(Guid instanceId);

  //CRhRdkContent* Rdk_FindRhCmnContentPointer(int serial_number, int* search_hint)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_FindRhCmnContentPointer(int serial_number, ref int search_hint);

  //int Rdk_RenderContent_ParameterType(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_ParameterType(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int Rdk_RenderContent_GetBooleanParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_GetBooleanParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int Rdk_RenderContent_GetIntegerParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_GetIntegerParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //float Rdk_RenderContent_GetFloatParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern float Rdk_RenderContent_GetFloatParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //double Rdk_RenderContent_GetDoubleParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_RenderContent_GetDoubleParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //void Rdk_RenderContent_GetStringParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, CRhCmnStringHolder* pSH)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetStringParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, IntPtr pSH);

  //void Rdk_RenderContent_GetVector2dParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_2dVector* pV)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetVector2dParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Vector2d pV);

  //void Rdk_RenderContent_GetVector3dParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_3dVector* pV)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetVector3dParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Vector3d pV);

  //void Rdk_RenderContent_GetPoint4dParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_4dPoint* pP)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetPoint4dParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Point4d pP);

  //void Rdk_RenderContent_GetColorParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_4fPoint* pP)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetColorParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Color4f pP);

  //ON_UUID Rdk_RenderContent_GetUUIDParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_RenderContent_GetUUIDParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //void Rdk_RenderContent_GetMatrixParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_Xform* pM)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetMatrixParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Transform pM);

  //void Rdk_RenderContent_GetTimeParameter(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_GetTimeParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int Rdk_RenderContent_CallParameterTypeBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_CallParameterTypeBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int Rdk_RenderContent_CallGetBooleanParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_CallGetBooleanParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int Rdk_RenderContent_CallGetIntegerParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_CallGetIntegerParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //float Rdk_RenderContent_CallGetFloatParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern float Rdk_RenderContent_CallGetFloatParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //double Rdk_RenderContent_CallGetDoubleParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_RenderContent_CallGetDoubleParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //void Rdk_RenderContent_CallGetStringParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, CRhCmnStringHolder* pSH)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_CallGetStringParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, IntPtr pSH);

  //void Rdk_RenderContent_CallGetVector2dParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_2dVector* pV)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_CallGetVector2dParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Vector2d pV);

  //void Rdk_RenderContent_CallGetVector3dParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_3dVector* pV)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_CallGetVector3dParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Vector3d pV);

  //void Rdk_RenderContent_CallGetPoint4dParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_4dPoint* pP)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_CallGetPoint4dParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Point4d pP);

  //void Rdk_RenderContent_CallGetColorParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_4fPoint* pP)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_CallGetColorParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Color4f pP);

  //ON_UUID Rdk_RenderContent_CallGetUUIDParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_RenderContent_CallGetUUIDParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //void Rdk_RenderContent_CallGetMatrixParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_Xform* pM)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_CallGetMatrixParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, ref Transform pM);

  //void Rdk_RenderContent_CallGetTimeParameterBase(const CRhRdkContent* pContent, const RHMONO_STRING* _ps)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_CallGetTimeParameterBase(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps);

  //int Rdk_RenderContent_SetBoolParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, bool v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetBoolParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, [MarshalAs(UnmanagedType.U1)]bool v, int cc);

  //int Rdk_RenderContent_SetIntParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, int v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetIntParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, int v, int cc);

  //int Rdk_RenderContent_SetFloatParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, float v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetFloatParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, float v, int cc);

  //int Rdk_RenderContent_SetDoubleParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, double v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetDoubleParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, double v, int cc);

  //int Rdk_RenderContent_SetStringParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, const RHMONO_STRING* _psValue, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetStringParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, [MarshalAs(UnmanagedType.LPWStr)]string _psValue, int cc);

  //int Rdk_RenderContent_SetVector2dParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_2DVECTOR_STRUCT _v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetVector2dParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, Vector2d _v, int cc);

  //int Rdk_RenderContent_SetVector3dParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_3DVECTOR_STRUCT _v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetVector3dParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, Vector3d _v, int cc);

  //int Rdk_RenderContent_SetPoint4dParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_4DPOINT_STRUCT _v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetPoint4dParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, Point4d _v, int cc);

  //int Rdk_RenderContent_SetColorParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_4FVECTOR_STRUCT _v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetColorParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, Color4f _v, int cc);

  //int Rdk_RenderContent_SetMatrixParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_XFORM_STRUCT _v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetMatrixParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, Transform _v, int cc);

  //int Rdk_RenderContent_SetUUIDParameter(CRhRdkContent* pContent, const RHMONO_STRING* _ps, ON_UUID v, int cc)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_RenderContent_SetUUIDParameter(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _ps, Guid v, int cc);

  //ON_UUID Rdk_RenderContent_ObjectMaterialInstanceId(const CRhinoObject* pObject)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_RenderContent_ObjectMaterialInstanceId(IntPtr pObject);

  //void Rdk_RenderContent_SetObjectMaterialInstanceid(CRhinoObject* pObject, ON_UUID uuidInstanceId)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_SetObjectMaterialInstanceid(IntPtr pObject, Guid uuidInstanceId);

  //ON_UUID Rdk_RenderContent_LayerMaterialInstanceId(const ON_Layer* _pLayer)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_RenderContent_LayerMaterialInstanceId(IntPtr _pLayer);

  //void Rdk_RenderContent_SetLayerMaterialInstanceId(ON_Layer* _pLayer, ON_UUID uuid)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderContent_SetLayerMaterialInstanceId(IntPtr _pLayer, Guid uuid);
  #endregion


  #region rdk_contentfield.cpp
  //CRhRdkContentField* Rdk_ContentField_New(CRhRdkContent* pParent, const RHMONO_STRING* _pInternal, const RHMONO_STRING* _pFriendly, int iId)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_ContentField_New(IntPtr pParent, [MarshalAs(UnmanagedType.LPWStr)]string _pInternal, [MarshalAs(UnmanagedType.LPWStr)]string _pFriendly, int iId);

  //void Rdk_ContentField_Delete(CRhRdkContentField* pField)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_Delete(IntPtr pField);

  //void Rdk_ContentField_StringValue(CRhRdkContentField* pField, CRhCmnStringHolder* pSH)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_StringValue(IntPtr pField, IntPtr pSH);

  //void Rdk_ContentField_SetStringValue(CRhRdkContentField* pField, const RHMONO_STRING* _pValue, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetStringValue(IntPtr pField, [MarshalAs(UnmanagedType.LPWStr)]string _pValue, int iCC);

  //int Rdk_ContentField_BoolValue(CRhRdkContentField* pField)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_ContentField_BoolValue(IntPtr pField);

  //void Rdk_ContentField_SetBoolValue(CRhRdkContentField* pField, int iBool, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetBoolValue(IntPtr pField, int iBool, int iCC);

  //int Rdk_ContentField_IntValue(CRhRdkContentField* pField)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_ContentField_IntValue(IntPtr pField);

  //void Rdk_ContentField_SetIntValue(CRhRdkContentField* pField, int i, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetIntValue(IntPtr pField, int i, int iCC);

  //double Rdk_ContentField_DoubleValue(CRhRdkContentField* pField)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_ContentField_DoubleValue(IntPtr pField);

  //void Rdk_ContentField_SetDoubleValue(CRhRdkContentField* pField, double d, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetDoubleValue(IntPtr pField, double d, int iCC);

  //float Rdk_ContentField_FloatValue(CRhRdkContentField* pField)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern float Rdk_ContentField_FloatValue(IntPtr pField);

  //void Rdk_ContentField_SetFloatValue(CRhRdkContentField* pField, float f, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetFloatValue(IntPtr pField, float f, int iCC);

  //ON_UUID Rdk_ContentField_UUIDValue(CRhRdkContentField* pField)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_ContentField_UUIDValue(IntPtr pField);

  //void Rdk_ContentField_SetUUIDValue(CRhRdkContentField* pField, ON_UUID v, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetUUIDValue(IntPtr pField, Guid v, int iCC);

  //void Rdk_ContentField_ColorValue(CRhRdkContentField* pField, ON_4fPoint* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_ColorValue(IntPtr pField, ref Color4f p);

  //void Rdk_ContentField_SetColorValue(CRhRdkContentField* pField, ON_4FVECTOR_STRUCT v, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetColorValue(IntPtr pField, Color4f v, int iCC);

  //void Rdk_ContentField_Vector2dValue(CRhRdkContentField* pField, ON_2dVector* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_Vector2dValue(IntPtr pField, ref Vector2d p);

  //void Rdk_ContentField_SetVector2dValue(CRhRdkContentField* pField, ON_2DVECTOR_STRUCT v, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetVector2dValue(IntPtr pField, Vector2d v, int iCC);

  //void Rdk_ContentField_Vector3dValue(CRhRdkContentField* pField, ON_3dVector* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_Vector3dValue(IntPtr pField, ref Vector3d p);

  //void Rdk_ContentField_SetVector3dValue(CRhRdkContentField* pField, ON_3DVECTOR_STRUCT v, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetVector3dValue(IntPtr pField, Vector3d v, int iCC);

  //void Rdk_ContentField_Point4dValue(CRhRdkContentField* pField, ON_4dPoint* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_Point4dValue(IntPtr pField, ref Point4d p);

  //void Rdk_ContentField_SetPoint4dValue(CRhRdkContentField* pField, ON_4DPOINT_STRUCT v, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetPoint4dValue(IntPtr pField, Point4d v, int iCC);

  //void Rdk_ContentField_XformValue(CRhRdkContentField* pField, ON_Xform* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_XformValue(IntPtr pField, ref Transform p);

  //void Rdk_ContentField_SetXformValue(CRhRdkContentField* pField, ON_XFORM_STRUCT xform, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetXformValue(IntPtr pField, Transform xform, int iCC);

  //void Rdk_ContentField_TimeValue(  CRhRdkContentField* pField, 
  //												int* piYearOut, int* piMonthOut, int* piDayOut, 
  //												int* piHoursOut, int* piMinutesOut, int* piSecondsOut)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_TimeValue(IntPtr pField, ref int piYearOut, ref int piMonthOut, ref int piDayOut, ref int piHoursOut, ref int piMinutesOut, ref int piSecondsOut);

  //void Rdk_ContentField_SetTimeValue(CRhRdkContentField* pField, 
  //											int iYear, int iMonth, int iDay, int iHours, int iMinutes, int iSeconds, int iCC)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_ContentField_SetTimeValue(IntPtr pField, int iYear, int iMonth, int iDay, int iHours, int iMinutes, int iSeconds, int iCC);
  #endregion


  #region rdk_corecontent.cpp
  //bool Rdk_CoreContent_AddAutomaticUISection(CRhRdkContent* pContent, const RHMONO_STRING* _pCaption, int iId)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_CoreContent_AddAutomaticUISection(IntPtr pContent, [MarshalAs(UnmanagedType.LPWStr)]string _pCaption, int iId);
  #endregion


  #region rdk_environment.cpp
  //void Rdk_SetSimulateEnvironmentCallback(RDK_SIMULATEENVIRONMENTPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //int CRhCmnEnvironment_New(int serial_number, bool image_based, ON_UUID render_engine_id, ON_UUID plugin_id, ON_UUID type_id, int category)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int CRhCmnEnvironment_New(int serial_number, [MarshalAs(UnmanagedType.U1)]bool image_based, Guid render_engine_id, Guid plugin_id, Guid type_id, int category);

  //void Rdk_RenderEnvironment_CallSimulateEnvironmentBase(CRhRdkEnvironment* pEnvironment, CRhRdkSimulatedEnvironment* pSim, bool bForDataDec)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderEnvironment_CallSimulateEnvironmentBase(IntPtr pEnvironment, IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool bForDataDec);

  //void Rdk_RenderEnvironment_SimulateEnvironment(CRhRdkEnvironment* pEnvironment, CRhRdkSimulatedEnvironment* pSim, bool bForDataDec)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderEnvironment_SimulateEnvironment(IntPtr pEnvironment, IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool bForDataDec);
  #endregion


  #region rdk_groundplane.cpp
  //bool Rdk_GroundPlane_Enabled()
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_GroundPlane_Enabled();

  //void Rdk_GroundPlane_SetEnabled(bool v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_SetEnabled([MarshalAs(UnmanagedType.U1)]bool v);

  //double Rdk_GroundPlane_Altitude()
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_GroundPlane_Altitude();

  //void Rdk_GroundPlane_SetAltitude(double v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_SetAltitude(double v);

  //ON_UUID Rdk_GroundPlane_MaterialInstanceId()
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_GroundPlane_MaterialInstanceId();

  //void Rdk_GroundPlane_SetMaterialInstanceId(ON_UUID v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_SetMaterialInstanceId(Guid v);

  //void Rdk_GroundPlane_TextureOffset(ON_2dVector* pVector)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_TextureOffset(ref Vector2d pVector);

  //void Rdk_GroundPlane_SetTextureOffset(ON_2DVECTOR_STRUCT v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_SetTextureOffset(Vector2d v);

  //void Rdk_GroundPlane_TextureSize(ON_2dVector* pVector)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_TextureSize(ref Vector2d pVector);

  //void Rdk_GroundPlane_SetTextureSize(ON_2DVECTOR_STRUCT v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_SetTextureSize(Vector2d v);

  //double Rdk_GroundPlane_TextureRotation()
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_GroundPlane_TextureRotation();

  //void Rdk_GroundPlane_SetTextureRotation(double v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_GroundPlane_SetTextureRotation(double v);
  #endregion


  #region rdk_material.cpp
  //void Rdk_SetTextureChildSlotNameCallback(RDK_TEXTURECHILDSLOTNAMEPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetSimulateMaterialCallback(RDK_SIMULATEMATERIALPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //int CRhCmnMaterial_New(int serial_number, bool image_based, ON_UUID render_engine_id, ON_UUID plugin_id, ON_UUID type_id, int category)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int CRhCmnMaterial_New(int serial_number, [MarshalAs(UnmanagedType.U1)]bool image_based, Guid render_engine_id, Guid plugin_id, Guid type_id, int category);

  //void Rdk_RenderMaterial_CallTextureChildSlotNameBase(CRhRdkMaterial* pMaterial, CRhCmnStringHolder* pSH, int which)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderMaterial_CallTextureChildSlotNameBase(IntPtr pMaterial, IntPtr pSH, int which);

  //void Rdk_RenderMaterial_CallSimulateMaterialBase(CRhRdkMaterial* pMaterial, ON_Material* pSim, bool bForDataDec)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderMaterial_CallSimulateMaterialBase(IntPtr pMaterial, IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool bForDataDec);

  //void Rdk_RenderMaterial_SimulateMaterial(CRhRdkMaterial* pMaterial, ON_Material* pSim, bool bForDataDec)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderMaterial_SimulateMaterial(IntPtr pMaterial, IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool bForDataDec);
  #endregion


  #region rdk_plugin.cpp
  //void Rdk_SetNewTextureCallback(RDK_NEWTEXTUREPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetNewMaterialCallback(RDK_NEWMATERIALPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetNewEnvironmentCallback(RDK_NEWENVIRONMENTPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //CRhCmnRdkPlugIn* CRhCmnRdkPlugIn_New( CRhinoPlugIn* pRhinoPlugIn )
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr CRhCmnRdkPlugIn_New(IntPtr pRhinoPlugIn);

  //void Rdk_AddTextureFactory(ON_UUID content_id)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_AddTextureFactory(Guid content_id);

  //void Rdk_AddMaterialFactory(ON_UUID content_id)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_AddMaterialFactory(Guid content_id);

  //void Rdk_AddEnvironmentFactory(ON_UUID content_id)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_AddEnvironmentFactory(Guid content_id);

  //ON_UUID Rdk_MaterialFromOnMaterial(const ON_Material* pMaterial)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_MaterialFromOnMaterial(IntPtr pMaterial);

  //void Rdk_SetMaterialToOnMaterial(ON_Material* pMaterial, ON_UUID uuid)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SetMaterialToOnMaterial(IntPtr pMaterial, Guid uuid);
  #endregion


  #region rdk_protoonenvironment.cpp
  //CRhRdkSimulatedEnvironment* Rdk_SimulatedEnvironment_New()
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_SimulatedEnvironment_New();

  //void Rdk_SimulatedEnvironment_Delete(CRhRdkSimulatedEnvironment* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedEnvironment_Delete(IntPtr p);

  //const CRhRdkSimulatedTexture* Rdk_SimulatedEnvironment_Texture(CRhRdkSimulatedEnvironment* pEnvironment)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_SimulatedEnvironment_Texture(IntPtr pEnvironment);

  //int Rdk_SimulatedEnvironment_BackgroundColor(CRhRdkSimulatedEnvironment* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_SimulatedEnvironment_BackgroundColor(IntPtr p);

  //void Rdk_SimulatedEnvironment_SetBackgroundColor(CRhRdkSimulatedEnvironment* p, int c)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedEnvironment_SetBackgroundColor(IntPtr p, int c);

  //void Rdk_SimulatedEnvironment_SetBackgroundImage(CRhRdkSimulatedEnvironment* p, CRhRdkSimulatedTexture* pTexture)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedEnvironment_SetBackgroundImage(IntPtr p, IntPtr pTexture);

  //int Rdk_SimulatedEnvironment_BackgroundProjection(CRhRdkSimulatedEnvironment* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_SimulatedEnvironment_BackgroundProjection(IntPtr p);

  //void Rdk_SimulatedEnvironment_SetBackgroundProjection(CRhRdkSimulatedEnvironment* p, int i)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedEnvironment_SetBackgroundProjection(IntPtr p, int i);

  //int Rdk_SimulatedEnvironment_ProjectionFromString(const RHMONO_STRING* _p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_SimulatedEnvironment_ProjectionFromString([MarshalAs(UnmanagedType.LPWStr)]string _p);

  //void Rdk_SimulatedTexture_StringFromProjection(CRhCmnStringHolder* pSH, int proj)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_StringFromProjection(IntPtr pSH, int proj);

  //int Rdk_SimulatedEnvironment_AutomaticProjectionFromChildTexture(ON_UUID uuidInstanceId)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_SimulatedEnvironment_AutomaticProjectionFromChildTexture(Guid uuidInstanceId);
  #endregion


  #region rdk_simulatedtexture.cpp
  //CRhRdkSimulatedTexture* Rdk_SimulatedTexture_New()
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_SimulatedTexture_New();

  //void Rdk_SimulatedTexture_Delete(CRhRdkSimulatedTexture* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_Delete(IntPtr p);

  //void Rdk_SimulatedTexture_LocalMappingTransform(CRhRdkSimulatedTexture* pSim, ON_Xform* pXform)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_LocalMappingTransform(IntPtr pSim, ref Transform pXform);

  //void Rdk_SimulatedTexture_Filename(CRhRdkSimulatedTexture* pSim, CRhCmnStringHolder* pSH)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_Filename(IntPtr pSim, IntPtr pSH);

  //void Rdk_SimulatedTexture_SetFilename(CRhRdkSimulatedTexture* pSim, const RHMONO_STRING* _pFilename)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetFilename(IntPtr pSim, [MarshalAs(UnmanagedType.LPWStr)]string _pFilename);

  //void Rdk_SimulatedTexture_OriginalFilename(CRhRdkSimulatedTexture* pSim, CRhCmnStringHolder* pSH)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_OriginalFilename(IntPtr pSim, IntPtr pSH);

  //void Rdk_SimulatedTexture_Repeat(CRhRdkSimulatedTexture* pSim, ON_2dVector* pVector)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_Repeat(IntPtr pSim, ref Vector2d pVector);

  //void Rdk_SimulatedTexture_SetRepeat(CRhRdkSimulatedTexture* pSim, ON_2DVECTOR_STRUCT v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetRepeat(IntPtr pSim, Vector2d v);

  //void Rdk_SimulatedTexture_Offset(CRhRdkSimulatedTexture* pSim, ON_2dVector* pVector)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_Offset(IntPtr pSim, ref Vector2d pVector);

  //void Rdk_SimulatedTexture_SetOffset(CRhRdkSimulatedTexture* pSim, ON_2DVECTOR_STRUCT v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetOffset(IntPtr pSim, Vector2d v);

  //double Rdk_SimulatedTexture_Rotation(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_SimulatedTexture_Rotation(IntPtr pSim);

  //void Rdk_SimulatedTexture_SetRotation(CRhRdkSimulatedTexture* pSim, double v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetRotation(IntPtr pSim, double v);

  //bool Rdk_SimulatedTexture_Repeating(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_SimulatedTexture_Repeating(IntPtr pSim);

  //void Rdk_SimulatedTexture_SetRepeating(CRhRdkSimulatedTexture* pSim, bool v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetRepeating(IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool v);

  //int Rdk_SimulatedTexture_MappingChannel(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_SimulatedTexture_MappingChannel(IntPtr pSim);

  //void Rdk_SimulatedTexture_SetMappingChannel(CRhRdkSimulatedTexture* pSim, int v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetMappingChannel(IntPtr pSim, int v);

  //int Rdk_SimulatedTexture_ProjectionMode(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_SimulatedTexture_ProjectionMode(IntPtr pSim);

  //void Rdk_SimulatedTexture_SetProjectionMode(CRhRdkSimulatedTexture* pSim, int v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetProjectionMode(IntPtr pSim, int v);

  //bool Rdk_SimulatedTexture_HasTransparentColor(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_SimulatedTexture_HasTransparentColor(IntPtr pSim);

  //void Rdk_SimulatedTexture_SetHasTransparentColor(CRhRdkSimulatedTexture* pSim, bool v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetHasTransparentColor(IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool v);

  //void Rdk_SimulatedTexture_TransparentColor(CRhRdkSimulatedTexture* pSim, ON_4fPoint* p)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_TransparentColor(IntPtr pSim, ref Color4f p);

  //void Rdk_SimulatedTexture_SetTransparentColor(CRhRdkSimulatedTexture* pSim, ON_4FVECTOR_STRUCT v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetTransparentColor(IntPtr pSim, Color4f v);

  //double Rdk_SimulatedTexture_TransparentColorSensitivity(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_SimulatedTexture_TransparentColorSensitivity(IntPtr pSim);

  //void Rdk_SimulatedTexture_SetTransparentColorSensitivity(CRhRdkSimulatedTexture* pSim, double v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetTransparentColorSensitivity(IntPtr pSim, double v);

  //bool Rdk_SimulatedTexture_Filtered(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_SimulatedTexture_Filtered(IntPtr pSim);

  //void Rdk_SimulatedTexture_SetFiltered(CRhRdkSimulatedTexture* pSim, bool v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SimulatedTexture_SetFiltered(IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool v);

  //double Rdk_SimulatedTexture_UnitsToMeters(CRhRdkSimulatedTexture* pSim, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_SimulatedTexture_UnitsToMeters(IntPtr pSim, double d);

  //double Rdk_SimulatedTexture_MetersToUnits(CRhRdkSimulatedTexture* pSim, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_SimulatedTexture_MetersToUnits(IntPtr pSim, double d);

  //ON_Texture* Rdk_SimulatedTexture_OnTexturePointer(CRhRdkSimulatedTexture* pSim)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_SimulatedTexture_OnTexturePointer(IntPtr pSim);
  #endregion


  #region rdk_sun.cpp
  //CRhRdkSun* Rdk_SunNew()
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_SunNew();

  //void Rdk_SunDelete(CRhRdkSun* pSun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_SunDelete(IntPtr pSun);

  //const IRhRdkSun* Rdk_SunInterface(const CRhRdkSun* pConstSun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_SunInterface(IntPtr pConstSun);

  //const IRhRdkSun* Rdk_DocSunInterface(int doc_id)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_DocSunInterface(int doc_id);

  //const CRhRdkDocSun* Rdk_DocSun(int doc_id)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_DocSun(int doc_id);

  //bool Rdk_Sun_Enabled(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_Enabled(IntPtr pConstISun);

  //void Rdk_Sun_SetEnabled(IRhRdkSun* pISun, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetEnabled(IntPtr pISun, [MarshalAs(UnmanagedType.U1)]bool b);

  //bool Rdk_Sun_EnableAllowed(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_EnableAllowed(IntPtr pConstISun);

  //void Rdk_Sun_SetEnableAllowed(IRhRdkSun* pISun, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetEnableAllowed(IntPtr pISun, [MarshalAs(UnmanagedType.U1)]bool b);

  //bool Rdk_Sun_ManualControlAllowed(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_ManualControlAllowed(IntPtr pConstISun);

  //void Rdk_Sun_SetManualControlAllowed(IRhRdkSun* pISun, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetManualControlAllowed(IntPtr pISun, [MarshalAs(UnmanagedType.U1)]bool b);

  //bool Rdk_Sun_ManualControlOn(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_ManualControlOn(IntPtr pConstISun);

  //void Rdk_Sun_SetManualControlOn(IRhRdkSun* pISun, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetManualControlOn(IntPtr pISun, [MarshalAs(UnmanagedType.U1)]bool b);

  //double Rdk_Sun_North(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_Sun_North(IntPtr pConstISun);

  //void Rdk_Sun_SetNorth(IRhRdkSun* pISun, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetNorth(IntPtr pISun, double d);

  //void Rdk_Sun_Vector(const IRhRdkSun* pConstISun, ON_3dVector* pVector)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_Vector(IntPtr pConstISun, ref Vector3d pVector);

  //void Rdk_Sun_SetVector(IRhRdkSun* pISun, ON_3DVECTOR_STRUCT v)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetVector(IntPtr pISun, Vector3d v);

  //double Rdk_Sun_Azimuth(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_Sun_Azimuth(IntPtr pConstISun);

  //void Rdk_Sun_SetAzimuth(IRhRdkSun* pISun, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetAzimuth(IntPtr pISun, double d);

  //double Rdk_Sun_Altitude(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_Sun_Altitude(IntPtr pConstISun);

  //void Rdk_Sun_SetAltitude(IRhRdkSun* pISun, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetAltitude(IntPtr pISun, double d);

  //double Rdk_Sun_Latitude(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_Sun_Latitude(IntPtr pConstISun);

  //void Rdk_Sun_SetLatitude(IRhRdkSun* pISun, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetLatitude(IntPtr pISun, double d);

  //double Rdk_Sun_Longitude(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_Sun_Longitude(IntPtr pConstISun);

  //void Rdk_Sun_SetLongitude(IRhRdkSun* pISun, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetLongitude(IntPtr pISun, double d);

  //double Rdk_Sun_TimeZone(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_Sun_TimeZone(IntPtr pConstISun);

  //void Rdk_Sun_SetTimeZone(IRhRdkSun* pISun, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetTimeZone(IntPtr pISun, double d);

  //bool Rdk_Sun_DaylightSavingOn(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_DaylightSavingOn(IntPtr pConstISun);

  //void Rdk_Sun_SetDaylightSavingOn(IRhRdkSun* pISun, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetDaylightSavingOn(IntPtr pISun, [MarshalAs(UnmanagedType.U1)]bool b);

  //int Rdk_Sun_DaylightSavingMinutes(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int Rdk_Sun_DaylightSavingMinutes(IntPtr pConstISun);

  //void Rdk_Sun_SetDaylightSavingMinutes(IRhRdkSun* pISun, int i)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetDaylightSavingMinutes(IntPtr pISun, int i);

  //void Rdk_Sun_LocalDateTime(const IRhRdkSun* pConstISun, 
  //										 int* piYearOut, int* piMonthOut, int* piDayOut, 
  //										 int* piHoursOut, int* piMinutesOut, int* piSecondsOut)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_LocalDateTime(IntPtr pConstISun, ref int piYearOut, ref int piMonthOut, ref int piDayOut, ref int piHoursOut, ref int piMinutesOut, ref int piSecondsOut);

  //void Rdk_Sun_SetLocalDateTime(IRhRdkSun* pISun, 
  //											int iYear, int iMonth, int iDay, int iHours, int iMinutes, int iSeconds)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetLocalDateTime(IntPtr pISun, int iYear, int iMonth, int iDay, int iHours, int iMinutes, int iSeconds);

  //void Rdk_Sun_UTCDateTime(const IRhRdkSun* pConstISun, 
  //										 int* piYearOut, int* piMonthOut, int* piDayOut, 
  //										 int* piHoursOut, int* piMinutesOut, int* piSecondsOut)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_UTCDateTime(IntPtr pConstISun, ref int piYearOut, ref int piMonthOut, ref int piDayOut, ref int piHoursOut, ref int piMinutesOut, ref int piSecondsOut);

  //void Rdk_Sun_SetUTCDateTime(IRhRdkSun* pISun, 
  //											int iYear, int iMonth, int iDay, int iHours, int iMinutes, int iSeconds)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetUTCDateTime(IntPtr pISun, int iYear, int iMonth, int iDay, int iHours, int iMinutes, int iSeconds);

  //void Rdk_Sun_Light(const IRhRdkSun* pConstISun, ON_Light* pLight)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_Light(IntPtr pConstISun, IntPtr pLight);

  //unsigned int Rdk_Sun_CRC(const IRhRdkSun* pConstISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern uint Rdk_Sun_CRC(IntPtr pConstISun);

  //void Rdk_Sun_ShowDialog(IRhRdkSun* pISun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_ShowDialog(IntPtr pISun);

  //bool Rdk_Sun_SkylightOn(const CRhRdkDocSun* pConstDocSun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_SkylightOn(IntPtr pConstDocSun);

  //void Rdk_Sun_SetSkylightOn(CRhRdkDocSun* pDocSun, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetSkylightOn(IntPtr pDocSun, [MarshalAs(UnmanagedType.U1)]bool b);

  //double Rdk_Sun_SkylightShadowIntensity(const CRhRdkDocSun* pConstDocSun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern double Rdk_Sun_SkylightShadowIntensity(IntPtr pConstDocSun);

  //void Rdk_Sun_SetSkylightShadowIntensity(CRhRdkDocSun* pDocSun, double d)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetSkylightShadowIntensity(IntPtr pDocSun, double d);

  //bool Rdk_Sun_SkylightCustomEnvironmentOn(const CRhRdkDocSun* pConstDocSun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_SkylightCustomEnvironmentOn(IntPtr pConstDocSun);

  //void Rdk_Sun_SetSkylightCustomEnvironmentOn(CRhRdkDocSun* pDocSun, bool b)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetSkylightCustomEnvironmentOn(IntPtr pDocSun, [MarshalAs(UnmanagedType.U1)]bool b);

  //ON_UUID Rdk_Sun_SkylightCustomEnvironment(const CRhRdkDocSun* pConstDocSun)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern Guid Rdk_Sun_SkylightCustomEnvironment(IntPtr pConstDocSun);

  //void Rdk_Sun_SetSkylightCustomEnvironment(CRhRdkDocSun* pDocSun, ON_UUID uuid)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_Sun_SetSkylightCustomEnvironment(IntPtr pDocSun, Guid uuid);

  //bool Rdk_Sun_IsSunLight(ON_Light* pLight)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_Sun_IsSunLight(IntPtr pLight);
  #endregion


  #region rdk_texture.cpp
  //void Rdk_SetNewTextureEvaluatorCallback(RDK_NEWTEXTUREEVALUATORPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //void Rdk_SetSimulateTextureCallback(RDK_SIMULATETEXTUREPROC proc)
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //int CRhCmnTexture_New(int serial_number, bool image_based, ON_UUID render_engine_id, ON_UUID plugin_id, ON_UUID type_id, int category)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int CRhCmnTexture_New(int serial_number, [MarshalAs(UnmanagedType.U1)]bool image_based, Guid render_engine_id, Guid plugin_id, Guid type_id, int category);

  //void Rdk_RenderTexture_AddTwoColorSection(CRhRdkContent* pContent)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderTexture_AddTwoColorSection(IntPtr pContent);

  //void Rdk_RenderTexture_LocalMappingTransform(CRhRdkTexture* pTex, ON_Xform* pXform)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderTexture_LocalMappingTransform(IntPtr pTex, ref Transform pXform);

  //IRhRdkTextureEvaluator* Rdk_RenderTexture_NewTextureEvaluator(CRhRdkTexture* pTex)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr Rdk_RenderTexture_NewTextureEvaluator(IntPtr pTex);

  //void Rdk_RenderTexture_CallSimulateTextureBase(CRhRdkTexture* pTexture, CRhRdkSimulatedTexture* pSim, bool bForDataDec)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderTexture_CallSimulateTextureBase(IntPtr pTexture, IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool bForDataDec);

  //void Rdk_RenderTexture_SimulateTexture(CRhRdkTexture* pTexture, CRhRdkSimulatedTexture* pSim, bool bForDataDec)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_RenderTexture_SimulateTexture(IntPtr pTexture, IntPtr pSim, [MarshalAs(UnmanagedType.U1)]bool bForDataDec);
  #endregion


  #region rdk_textureevaluator.cpp
  //void Rdk_SetTextureEvaluatorCallbacks( RDK_GETCOLORPROC cb, RDK_TEXTUREEVALDELETETHISPROC deletethis_cb )
  // SKIPPING - Contains a function pointer which needs to be written by hand

  //CRhCmnTextureEvaluator* CRhCmnRdkTextureEvaluator_New(int serial_number)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern IntPtr CRhCmnRdkTextureEvaluator_New(int serial_number);

  //int CRhCmnRdkTextureEvaluator_IsRhCmnEvaluator(const IRhRdkTextureEvaluator* pConstTextureEvaluator)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern int CRhCmnRdkTextureEvaluator_IsRhCmnEvaluator(IntPtr pConstTextureEvaluator);

  //bool Rdk_TextureEvaluator_GetColor(const IRhRdkTextureEvaluator* pConstTextureEvaluator, ON_3DPOINT_STRUCT uvw, ON_3DVECTOR_STRUCT duvwdx, ON_3DVECTOR_STRUCT duvwdy, ON_4fPoint* color)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  [return: MarshalAs(UnmanagedType.U1)]
  internal static extern bool Rdk_TextureEvaluator_GetColor(IntPtr pConstTextureEvaluator, Point3d uvw, Vector3d duvwdx, Vector3d duvwdy, ref Color4f color);

  //void Rdk_TextureEvaluator_DeleteThis(IRhRdkTextureEvaluator* pTextureEvaluator)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern void Rdk_TextureEvaluator_DeleteThis(IntPtr pTextureEvaluator);
  #endregion


}
