// !!!DO NOT EDIT THIS FILE BY HAND!!!
// Create this file by running MethodGen.exe in the rhinocommon directory
// MethodGen.exe parses the cpp files in rhcommon_c to create C# callable
// function declarations

using System;
using System.Runtime.InteropServices;
using Rhino;
using Rhino.Geometry;
using Rhino.Geometry.Intersect;
using Rhino.Collections;

// Atuomatically generated function declarations for calling into
// the support 'C' DLL (rhcommon_c.dll).
internal partial class UnsafeNativeMethods
{
  #region rdk_color.cpp
  //unsigned int Rdk_ColorBlend(float t, unsigned int from_argb, unsigned int to_argb)
  [DllImport(Import.librdk, CallingConvention=CallingConvention.Cdecl )]
  internal static extern uint Rdk_ColorBlend(float t, uint from_argb, uint to_argb);
  #endregion


}
